server:
  port: 8004
  
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-demo
      auto-offset-reset: earliest  
    template:
      default-topic: kafkatopic
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
